"""init

Revision ID: 02532849bc1d
Revises: 
Create Date: 2025-11-06 20:19:16.815002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02532849bc1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=25), nullable=True),
    sa.Column('descripcion', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Rol_id'), 'Rol', ['id'], unique=False)
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=25), nullable=False),
    sa.Column('correo', sa.String(length=27), nullable=False),
    sa.Column('contrasenia', sa.String(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['Rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuario_id'), 'Usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Usuario_id'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_index(op.f('ix_Rol_id'), table_name='Rol')
    op.drop_table('Rol')
    # ### end Alembic commands ###
