"""crear tablas faltantes

Revision ID: 29bcf794518e
Revises: 02532849bc1d
Create Date: 2025-11-06 21:13:16.804883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bcf794518e'
down_revision: Union[str, Sequence[str], None] = '02532849bc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CategoriaProducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CategoriaProducto_id'), 'CategoriaProducto', ['id'], unique=False)
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoDocumentoID', sa.String(length=4), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=25), nullable=False),
    sa.Column('apellido', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(length=15), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=30), nullable=True),
    sa.Column('municipio', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('ocupacion', sa.String(length=20), nullable=True),
    sa.Column('telefono_emergencia', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.CheckConstraint("genero IN ('Masculino','Femenino','Otro')", name='ck_cliente_genero'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cliente_id'), 'Cliente', ['id'], unique=False)
    op.create_table('Empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoDocumento', sa.String(length=4), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('cargo', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Empleado_id'), 'Empleado', ['id'], unique=False)
    op.create_table('EstadoDeCita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EstadoDeCita_id'), 'EstadoDeCita', ['id'], unique=False)
    op.create_table('EstadoVenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EstadoVenta_id'), 'EstadoVenta', ['id'], unique=False)
    op.create_table('Marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Marca_id'), 'Marca', ['id'], unique=False)
    op.create_table('Permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=23), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Permiso_id'), 'Permiso', ['id'], unique=False)
    op.create_table('Proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_proveedor', sa.String(length=20), nullable=True),
    sa.Column('tipoDeDocumento', sa.String(length=4), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('razon_social_o_Nombre', sa.String(length=30), nullable=True),
    sa.Column('Contacto', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('correo', sa.String(length=50), nullable=True),
    sa.Column('departamento', sa.String(length=15), nullable=True),
    sa.Column('municipio', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.CheckConstraint("tipo_proveedor IN ('Persona Natural','Persona Jurídica')", name='ck_proveedor_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Proveedor_id'), 'Proveedor', ['id'], unique=False)
    op.create_table('Servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Servicio_id'), 'Servicio', ['id'], unique=False)
    op.create_table('Cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=True),
    sa.Column('servicioId', sa.Integer(), nullable=True),
    sa.Column('empleadoId', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=20), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('estadoDeCitaId', sa.Integer(), nullable=True),
    sa.CheckConstraint("metodo_pago IN ('Efectivo','Tarjeta','Transferencia')", name='ck_cita_metodo'),
    sa.ForeignKeyConstraint(['clienteId'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['empleadoId'], ['Empleado.id'], ),
    sa.ForeignKeyConstraint(['estadoDeCitaId'], ['EstadoDeCita.id'], ),
    sa.ForeignKeyConstraint(['servicioId'], ['Servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Cita_id'), 'Cita', ['id'], unique=False)
    op.create_table('Compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedorId', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('estadoCompra', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proveedorId'], ['Proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Compra_id'), 'Compra', ['id'], unique=False)
    op.create_table('HistorialDeFormula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('OD_Esfera', sa.String(length=20), nullable=True),
    sa.Column('OD_Cilindro', sa.String(length=20), nullable=True),
    sa.Column('OD_Eje', sa.String(length=20), nullable=True),
    sa.Column('OI_Esfera', sa.String(length=20), nullable=True),
    sa.Column('OI_Cilindro', sa.String(length=20), nullable=True),
    sa.Column('OI_Eje', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['clienteId'], ['Cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HistorialDeFormula_id'), 'HistorialDeFormula', ['id'], unique=False)
    op.create_table('Horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleadoId', sa.Integer(), nullable=True),
    sa.Column('horaInicio', sa.Time(), nullable=True),
    sa.Column('horaFinal', sa.Time(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empleadoId'], ['Empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Horario_id'), 'Horario', ['id'], unique=False)
    op.create_table('Producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoriaProductoId', sa.Integer(), nullable=True),
    sa.Column('marcaId', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoriaProductoId'], ['CategoriaProducto.id'], ),
    sa.ForeignKeyConstraint(['marcaId'], ['Marca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Producto_id'), 'Producto', ['id'], unique=False)
    op.create_table('permisoPorRol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=True),
    sa.Column('permisoId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permisoId'], ['Permiso.id'], ),
    sa.ForeignKeyConstraint(['rolId'], ['Rol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisoPorRol_id'), 'permisoPorRol', ['id'], unique=False)
    op.create_table('DetalleCompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compraId', sa.Integer(), nullable=True),
    sa.Column('productoId', sa.Integer(), nullable=True),
    sa.Column('precioUnidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['compraId'], ['Compra.id'], ),
    sa.ForeignKeyConstraint(['productoId'], ['Producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DetalleCompra_id'), 'DetalleCompra', ['id'], unique=False)
    op.create_table('Imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productosId', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['productosId'], ['Producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Imagenes_id'), 'Imagenes', ['id'], unique=False)
    op.create_table('Venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('estadoDeVentaId', sa.Integer(), nullable=True),
    sa.Column('citaId', sa.Integer(), nullable=True),
    sa.Column('empleadoId', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=True),
    sa.Column('totalVenta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['citaId'], ['Cita.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['empleadoId'], ['Empleado.id'], ),
    sa.ForeignKeyConstraint(['estadoDeVentaId'], ['EstadoVenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Venta_id'), 'Venta', ['id'], unique=False)
    op.create_table('Abono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ventaId', sa.Integer(), nullable=True),
    sa.Column('montoAbonado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ventaId'], ['Venta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Abono_id'), 'Abono', ['id'], unique=False)
    op.create_table('DetalleVenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productoId', sa.Integer(), nullable=True),
    sa.Column('VentaId', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precioUnitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['VentaId'], ['Venta.id'], ),
    sa.ForeignKeyConstraint(['productoId'], ['Producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DetalleVenta_id'), 'DetalleVenta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_DetalleVenta_id'), table_name='DetalleVenta')
    op.drop_table('DetalleVenta')
    op.drop_index(op.f('ix_Abono_id'), table_name='Abono')
    op.drop_table('Abono')
    op.drop_index(op.f('ix_Venta_id'), table_name='Venta')
    op.drop_table('Venta')
    op.drop_index(op.f('ix_Imagenes_id'), table_name='Imagenes')
    op.drop_table('Imagenes')
    op.drop_index(op.f('ix_DetalleCompra_id'), table_name='DetalleCompra')
    op.drop_table('DetalleCompra')
    op.drop_index(op.f('ix_permisoPorRol_id'), table_name='permisoPorRol')
    op.drop_table('permisoPorRol')
    op.drop_index(op.f('ix_Producto_id'), table_name='Producto')
    op.drop_table('Producto')
    op.drop_index(op.f('ix_Horario_id'), table_name='Horario')
    op.drop_table('Horario')
    op.drop_index(op.f('ix_HistorialDeFormula_id'), table_name='HistorialDeFormula')
    op.drop_table('HistorialDeFormula')
    op.drop_index(op.f('ix_Compra_id'), table_name='Compra')
    op.drop_table('Compra')
    op.drop_index(op.f('ix_Cita_id'), table_name='Cita')
    op.drop_table('Cita')
    op.drop_index(op.f('ix_Servicio_id'), table_name='Servicio')
    op.drop_table('Servicio')
    op.drop_index(op.f('ix_Proveedor_id'), table_name='Proveedor')
    op.drop_table('Proveedor')
    op.drop_index(op.f('ix_Permiso_id'), table_name='Permiso')
    op.drop_table('Permiso')
    op.drop_index(op.f('ix_Marca_id'), table_name='Marca')
    op.drop_table('Marca')
    op.drop_index(op.f('ix_EstadoVenta_id'), table_name='EstadoVenta')
    op.drop_table('EstadoVenta')
    op.drop_index(op.f('ix_EstadoDeCita_id'), table_name='EstadoDeCita')
    op.drop_table('EstadoDeCita')
    op.drop_index(op.f('ix_Empleado_id'), table_name='Empleado')
    op.drop_table('Empleado')
    op.drop_index(op.f('ix_Cliente_id'), table_name='Cliente')
    op.drop_table('Cliente')
    op.drop_index(op.f('ix_CategoriaProducto_id'), table_name='CategoriaProducto')
    op.drop_table('CategoriaProducto')
    # ### end Alembic commands ###
